metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.modules:
- module: elasticsearch
  metricsets:
    - node
    - node_stats
    - index
    - index_recovery
    - index_summary
    - ingest_pipeline
    - shard
    - ml_job
  period: 10s
  hosts: ["http://elastic1:9200","http://elastic2:9200"]
  username: "elastic"
  password: "QlGVo*CUuf2=24iTjZHN"

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["http://elastic1:9200","http://elastic2:9200"]
  username: "elastic"
  password: "QlGVo*CUuf2=24iTjZHN"
